// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPs1PowjSnofKdy_cImD0zv33tdM2IVY',
    appId: '1:1040516199155:android:daf8fb47bb21657bdc3d86',
    messagingSenderId: '1040516199155',
    projectId: 'findlo-2736e',
    storageBucket: 'findlo-2736e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVPs1PowjSnofKdy_cImD0zv33tdM2IVY',
    appId: '1:1040516199155:ios:81ce9be91c6d330adc3d86',
    messagingSenderId: '1040516199155',
    projectId: 'findlo-2736e',
    storageBucket: 'findlo-2736e.appspot.com',
    androidClientId: '1040516199155-sv389k6o73qjpk914a1skk0n594mjd4l.apps.googleusercontent.com',
    iosClientId: '1040516199155-eodcuhleku10dk9lnq28b7kotlm39p6j.apps.googleusercontent.com',
    iosBundleId: 'com.axiomanetwork.flutterTrabajo',
  );
}
