// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUkIu2li8dJyUPyy2iIHyYOQQt3PUz1oI',
    appId: '1:862054338294:android:2e66d16aa17206d88126d7',
    messagingSenderId: '862054338294',
    projectId: 'findlo-effce',
    storageBucket: 'findlo-effce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCExvIXqEziPeXbd6fTB1iboiOqJGY_Cow',
    appId: '1:862054338294:ios:f9eb214a0f264cdf8126d7',
    messagingSenderId: '862054338294',
    projectId: 'findlo-effce',
    storageBucket: 'findlo-effce.appspot.com',
    androidClientId: '862054338294-g7j3nfqoj87vqb9bnhn3j952pojiih1g.apps.googleusercontent.com',
    iosClientId: '862054338294-1ilppnujchf9h29808ih56ippq2aei4o.apps.googleusercontent.com',
    iosBundleId: 'com.axiomanetwork.flutterTrabajo',
  );
}
